# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np

np.random.seed(42)

num_samples = 10000

data = {
    'Transaction_ID': np.arange(1, num_samples + 1),
    'Amount': np.random.uniform(100, 50000, num_samples),  # Transaction amount
    'Tax_Reported': np.random.uniform(5, 30, num_samples),  # Tax reported by the company
    'Tax_Actual': np.random.uniform(5, 30, num_samples),    # Actual tax that should be paid
    'Category': np.random.choice(['Sales', 'Purchase', 'Salary', 'Investment'], num_samples),
    'Is_Anomalous': np.random.choice([0, 1], num_samples, p=[0.97, 0.03])  # 3% anomalies
}

df = pd.DataFrame(data)

df.loc[df['Is_Anomalous'] == 1, 'Tax_Reported'] *= np.random.uniform(1.5, 3.0)

df.to_csv("synthetic_financial_data.csv", index=False)

print("✅ Synthetic financial transaction data generated and saved to 'data/synthetic_financial_data.csv'!")